Repository net-daemon/net-hassclient, pull requests merged in 2021-05, with the labels that each got.

#117 Made HassState.Attribute init ReadOnlyDictionary
  src/HassClient/Helpers/Json/JsonExtensions.cs
  src/HassClient/Model/HassState.cs
  tests/HassClient.Unit.Tests/HassMessagesTests.cs
Labels: enhancement, pr: enhancement

#118 added support for trigger webhook
  console/HassClient.Performance.Tests/HassClient.Performance.Tests.csproj
  console/HassClient.Performance.Tests/Program.cs
  src/HassClient/Client/HassClient.cs
  tests/HassClient.Unit.Tests/HassClientTests.cs
Labels: pr: new-feature

#119 Fixes the bug in webhook
  src/HassClient/Client/HassClient.cs
Labels: pr: bugfix
